# Generated by Django 5.1.1 on 2024-09-13 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=255)),
                ('criacao', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proximo_numero', models.IntegerField(default=1)),
                ('operacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sequencia', to='ticket_app.operacoes')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.IntegerField()),
                ('criacao', models.DateField(auto_now_add=True)),
                ('placa', models.CharField(max_length=100)),
                ('transportadora', models.CharField(max_length=255)),
                ('motorista', models.CharField(max_length=255)),
                ('cliente', models.CharField(max_length=255)),
                ('peso_entrada', models.CharField(max_length=255)),
                ('peso_saida', models.CharField(max_length=255)),
                ('peso_liquido', models.CharField(max_length=255)),
                ('lote_leira', models.CharField(max_length=100)),
                ('ticket_cancelado', models.BooleanField(default=False)),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticket_app.operacoes')),
            ],
        ),
        migrations.CreateModel(
            name='UserOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresas', models.ManyToManyField(related_name='usuarios', to='ticket_app.operacoes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
