# Generated by Django 5.1.1 on 2024-09-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='peso_entrada',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='peso_liquido',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='peso_saida',
            field=models.FloatField(),
        ),
    ]
