# Generated by Django 5.1.1 on 2024-09-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0002_alter_tickets_peso_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='sequencia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
