# Generated by Django 5.1.1 on 2024-09-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0004_tickets_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='operador',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
