# Generated by Django 5.1.1 on 2024-09-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0005_tickets_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='produto',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
