# Generated by Django 5.1.1 on 2024-10-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0008_imagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='umidade',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
