# Generated by Django 5.1.1 on 2024-10-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0009_tickets_umidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='concluido',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
